server:
  port: 8003
spring:
  application:
    name: service-vod
  profiles:
    active: dev  #环境设置: dev,test,prod
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.199.100:8848 #服务地址

aliyun:
  vod:
    file:
      keyid: LTAI5tS6amFwgFinXXU9KMst
      keysecret: 9lJ2OsiEvYBeIXLQErVMNQMhDQQKgA