server:
  port: 8001
spring:
  application:
    name: service-edu
  profiles:
    active: dev  #环境设置: dev,test,prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli?serverTimezone=GMT%2B8
    username: root
    password: 148963
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.199.100:8848 #服务地址


mybatis-plus:
  global-config:
      db-config:
        id-type: ASSIGN_UUID
#    configuration:
#      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#
#
#logging:
#  level:
#    root: warn
